### ISSUE TITLE
The rendering process currently not working.

### ISSUE THREAD

**Issue by atimaly** [pveierland/project_euler_offline#1]
After I have run the fetching line, which completed successfully, the rendering process failed with the following message.

> Pandoc version 3.2.1 is not supported, we proceed as if pandoc 2.19.2 was used. 
The behavior of the library is undefined if the document models of these versions differ.
  warnings.warn(error)
Rendering problems...: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/atimaly/Downloads/project_euler_offline-master/project_euler_offline/__main__.py", line 3, in <module>
    ProjectEulerOfflineApp().run()
  File "/Users/atimaly/Downloads/project_euler_offline-master/project_euler_offline/app.py", line 236, in run
    self.command_render()
  File "/Users/atimaly/Downloads/project_euler_offline-master/project_euler_offline/app.py", line 108, in command_render
    document_builder.process_problem_html(problem_id, problem_html)
  File "/Users/atimaly/Downloads/project_euler_offline-master/project_euler_offline/document_builder.py", line 455, in process_problem_html
    + self._transform_html_to_latex(problem_content_html)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/atimaly/Downloads/project_euler_offline-master/project_euler_offline/document_builder.py", line 187, in _transform_html_to_latex
    document_latex = str(pandoc.write(document_pandoc, format="latex").strip())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/atimaly/anaconda3/lib/python3.11/site-packages/pandoc/__init__.py", line 355, in write
    pandoc(options)
  File "/Users/atimaly/anaconda3/lib/python3.11/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/atimaly/anaconda3/lib/python3.11/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "/Users/atimaly/anaconda3/lib/python3.11/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/atimaly/anaconda3/lib/python3.11/site-packages/plumbum/commands/processes.py", line 328, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/atimaly/anaconda3/lib/python3.11/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/Users/atimaly/anaconda3/lib/python3.11/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 64
Command line: | /usr/local/bin/pandoc -t latex -o /var/folders/dq/hdvh4n596vn47mldk70zc1fw0000gp/T/tmp1l1k3ofq/output -f json /var/folders/dq/hdvh4n596vn47mldk70zc1fw0000gp/T/tmp1l1k3ofq/input.js
Stderr:       | JSON parse error: Error in $: Incompatible API versions: encoded with [1,22,2,1] but attempted to decode with [1,23,1].

I am on mac.
I would appreciate the help on how to solve this.

**Comment by pveierland** [comment]
The development environment has now been updated. Feel free to test it again 👍
